return {
  "3rd/image.nvim",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    backend = "kitty",
    processor = "magick_cli",
    integrations = {
      markdown = {
        enabled = true,
        clear_in_insert_mode = false,
        download_remote_images = true,
        only_render_image_at_cursor = false,
        filetypes = { "markdown" },
      },
      html = { enabled = false },
      css = { enabled = false },
    },
    -- Explicit patterns for direct image opening (hijack buffer view)
    hijack_file_patterns = {
      "*.png",
      "*.jpg",
      "*.jpeg",
      "*.gif",
      "*.webp",
      "*.avif",
      "*.ico",
      "*.PNG",
      "*.JPG",
      "*.JPEG",
      "*.GIF",
      "*.WEBP",
      "*.AVIF",
      "*.ICO",
    },
    max_width = nil,
    max_height = 14,
    max_width_window_percentage = nil,
    max_height_window_percentage = 60,
    window_overlap_clear_enabled = true,
    window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "", "NvimTree" },
  },
}
